### ISSUE TITLE
As a system, I will have intuitive menus, so that I am easy to navigate.

### ISSUE THREAD

**Issue by capper0074** [Datamatiker2022-Team13/Riptos#26]
### Tasks
- [x] #52
- [x] #27 
- [x] #53
- [x] #37 

### Acceptance criteria
- [x] Each menus choices are indicative of what they lead to.
- [x] Menus are stable.

**Comment by jonwangholm** [comment]
Error handling findes i branchen 'ErrorHandlingMenu'.
