### ISSUE TITLE
Delete data (CRU'D')

### ISSUE THREAD

**Issue by capper0074** [Datamatiker2022-Team13/Riptos#31]
All the repositories should have a "Delete" method, if deemed necessary.
- [x] "Add" method implemented in the "EmployeeRepository" class.
- [x] ... "InquiryRepository" class.
- [ ] ... "CaseRepository" class.
- [ ] ... "MeetingRepository" class.

**Comment by KasperNissen1997** [comment]
No repositories made for cases or meetings yet, as they are out of scope.
